### PR TITLE
Quote of Doug Linder

### PR DESCRIPTION
**Pull request by grvpandey11**
Hi,

Thanks for this awesome plugin!

I wanted to add a quote I like, which is from Doug Linder.

Thanks

### CODE REVIEW

**Review by Parsifal-M — APPROVED** [review]
Love it! Nice one :smile:

**Comment by Parsifal-M** [comment]
Thank you so much for adding a quote! Would you please just sign the commit? :smile: here is a guide if you are not sure how https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by grvpandey11** [comment]
@Parsifal-M I think now it looks good.
Also, I think you have to help me in merging the Pull Request 😄

**Comment by Parsifal-M** [comment]
> @Parsifal-M I think now it looks good. Also, you have to help me in merging the Pull Request 😄

Merged! Tyvm!

**Pull request merged**
